TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: xxx
  FEISHU_APP_SECRET: xxxx
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
