TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: xxx
  FEISHU_APP_SECRET: xxx
APP_TOKEN_CACHE_KEY: FeiShuToken
MYSQLDB_CONFIG:
  type: mysql                      # 数据库链接类型
  host: "localhost"                 # 数据库链接地址
  port: 3306                         # 数据库链接端口
  username: "root"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "fast_gateway_test"      # 数据库名
  entities: "mysql"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
